apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudguard-model-pvc
  namespace: kubeflow-user
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard   # adjust to your cluster's storage class
