apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudguard-model-pvc
  namespace: kubeflow-mlops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  
